### ISSUE TITLE
Entity not available

### ISSUE THREAD

**Issue by milouzzzz** [fredericvl/py-agua-iot#11]
Hi there.
First of all thanks for your work.

I've set up your integration. I could login successfully and now i have my klover heater but the entity remains unavailable.
Any idea?

Thanks

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 711, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/aguaiot/climate.py", line 110, in device_state_attributes
    ATTR_SMOKE_TEMP: self._device.gas_temperature,
  File "/usr/local/lib/python3.9/site-packages/py_agua_iot/__init__.py", line 600, in gas_temperature
    return float(self.__get_information_item('temp_gas_flue_get'))
  File "/usr/local/lib/python3.9/site-packages/py_agua_iot/__init__.py", line 430, in __get_information_item
    formula = self.__register_map_dict[item]['formula']
KeyError: `'temp_gas_flue_get'
```

**Comment by dynalte** [comment]
Hi, 

I have the exact same problem, with a klover stove too.
Did you find a workaround ?

Thanks

**Comment by milouzzzz** [comment]
Hey
Nope...no luck so far.
The entity shows up but remains unavailable.

I suspect a communication problem with my stove.
When i check "stato wifi" on the stove remote control i have only zeros like if the stove wasn't connected to my network but i can control it with the app via wifi.

I never manage to register my stove on appwifi.klover.it, i don't know if this could be a problem as well.

**Comment by dynalte** [comment]
I finally resolved this problem.
I changed the gas_temperature return value to return always 0 rather than asking this value to the API
I forked this repository to make this change : https://github.com/dynalte/py-agua-iot

It would be preferable to update this repo with a better correction.

Btw, i also have the zeros in the wifi check on the remote control.

**Comment by milouzzzz** [comment]
Happy that there is a solution! well done.
I'm not sure to understand how to solve this in my config.

I installed the custom component like described in the readme file. I just moved the agua iot folder from the exmaple folder to my HA. I think i'm doing it wrong.

Sorry for beeing such a noob  :)

**Comment by milouzzzz** [comment]
thanks for your help.
I've done this but still have the same issue. The stove remains unavailable.

**Comment by milouzzzz** [comment]
Yes I did. Multiple times.
I also made a clean install. Nothing helps.

**Comment by milouzzzz** [comment]
i checked the logs. It's still the same error: 
KeyError: 'temp_gas_flue_get'

**Comment by milouzzzz** [comment]
solved
I had to edit the __init__.py directly with HassOS CLI.

**Comment by heddock** [comment]
@milouzzzz how did you edit the init.py file directly on the HassOS client? When i try to edit this via the SSH terminal there is no such file. Thanks in advance.

**Comment by milouzzzz** [comment]
> @milouzzzz how did you edit the init.py file directly on the HassOS client? When i try to edit this via the SSH terminal there is no such file. Thanks in advance.

It's because you need to have acces to the host OS. Look here : https://developers.home-assistant.io/docs/operating-system/debugging/

**Comment by heddock** [comment]
Thanks for your reply. I have been able to edit the file and the stove is working now. I hope there will be a more definite fix in the future.
