### ISSUE TITLE
Failed to update climate entity in Home Assistant

### ISSUE THREAD

**Issue by gzeel** [fredericvl/py-agua-iot#2]
Since the update to Home Assistant 2021.1.2 (and .3) I’m getting an error about the climate entity
`2021-01-15 16:25:08 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.woonkamer is taking over 10 seconds
2021-01-15 16:25:09 ERROR (SyncWorker_10) [custom_components.aguaiot.climate] Failed to update Woonkamer (XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX), error: Error while fetching device information `

(removed the mac address)
Maybe it has something to do with the introduced security filter for custom components in 2021.1.2?
Too bad there’s not more logging..

When I revert back to 2021.1.1 there’s no problem.

Update:
In the DNS logs i’m getting this. I will check if these logging will also appear in 2021.1.1
`[INFO] 172.30.32.1:34149 - 46194 "A IN jollymec.agua-iot.com. udp 39 false 512" SERVFAIL qr,rd,ra 39 0.009629505s
[INFO] 172.30.32.1:34149 - 46194 "A IN jollymec.agua-iot.com. udp 39 false 512" SERVFAIL qr,aa,rd,ra 39 0.000111789s
[INFO] 172.30.32.1:34149 - 46194 "A IN jollymec.agua-iot.com. udp 39 false 512" SERVFAIL qr,aa,rd,ra 39 0.00008112s
[INFO] 172.30.32.1:34149 - 46194 "A IN jollymec.agua-iot.com. udp 39 false 512" SERVFAIL qr,aa,rd,ra 39 0.000056371s
[INFO] 172.30.32.1:34149 - 46194 "A IN jollymec.agua-iot.com. udp 39 false 512" SERVFAIL qr,aa,rd,ra 39 0.00003734s
[INFO] 172.30.32.1:34149 - 46194 "A IN jollymec.agua-iot.com. udp 39 false 512" SERVFAIL qr,aa,rd,ra 39 0.00007462s
[INFO] 172.30.32.1:34149 - 46194 "A IN jollymec.agua-iot.com. udp 39 false 512" SERVFAIL qr,aa,rd,ra 39 0.000050235s
[INFO] 172.30.32.1:34149 - 46194 "A IN jollymec.agua-iot.com. udp 39 false 512" SERVFAIL qr,aa,rd,ra 39 0.000033277s
[INFO] 172.30.32.1:34149 - 46194 "A IN jollymec.agua-iot.com. udp 39 false 512" SERVFAIL qr,aa,rd,ra 39 0.000057828s
[INFO] 172.30.32.1:34149 - 46194 "A IN jollymec.agua-iot.com. udp 39 false 512" SERVFAIL qr,aa,rd,ra 39 0.000051985s `

**Comment by fredericvl** [comment]
Hi @gzeel ,

> Maybe it has something to do with the introduced security filter for custom components in 2021.1.2?

As far as I know HA logs a warning when the security filter prevents a web call, which I don't see in your log outputs...

I do currently not experience any issues with HA 2021.1.3 and cannot seem to reproduce them at my side.

Keep in mind that the Agua IOT servers can also have issues and when they are not responding (fast enough) you'll also see such errors from the integration.
Also in case of local or remote DNS issues this would be the case.
Unfortunately those are things I can't do anything about...

I'll close the issue for now but if it would evolve into an issue with AGUA IOT module itself it can of course be re-opened.

Grtz!
