### ISSUE TITLE
User input malformed

### ISSUE THREAD

**Issue by Gingerator** [fredericvl/py-agua-iot#21]
Hello,

First I want to thank you for your HA integration of the agua iot module. I used it for like 10 month and it was working perfectly.

I recently had to wipe all my HA and rebuild it from scratch. I'm currently running on the latest stable versions which means :

- Core : core-2021.11.3
- Supervisor : supervisor-2021.10.8
- Home Assistant OS 6.6

I have an EvaCalor stove with an AguaIOT T009 Navel 2.0 (https://www.micronovasrl.com/en/realizzazione/t009/).

I tried to add your integration (0.0.8) but I couldn't manage to make it work. Everytime I add the aguaiot folder and restart the HA, and try to add the integration I get this error :
![2021-11-12_10-43-15](https://user-images.githubusercontent.com/44290760/141447844-09b19564-9e47-4900-9afd-5082274d4197.png)

There are no blank space or something in the fields.

I read the issues on the page and I tried to add both folders (py-agua-iot and aguaiot from the example folder) in custom_components but I still have the same issue.

Am I doing something wrong or is it something related to the new HA updates ?

Thanks !

**Comment by milouzzzz** [comment]
Same here with core-2021.11.1 and core-2021.11.3

**Comment by robbiegoossens** [comment]
I have the same issue with a Nordic Fire 2.0

**Comment by Gingerator** [comment]
I tried with the newest versions of the core which are 2021.11.4 and 2021.11.5 still the same error message.

**Comment by Gingerator** [comment]
Hi,

@fredericvl did you encounter the issue or have any update about it ?

Still having "User input malformed" with versions from 0.0.1 to 0.0.8.

Many thanks.

**Comment by robbiegoossens** [comment]
Hi, I just updated to 2021.12, tested the integration again and still get an error:

"User input malformed: expected str for dictionary value @ data['brand_id']"

Can somebody provide some help ?

Many thanks.

**Comment by milouzzzz** [comment]
Got the same error with 2021.12.
I don't get the "user input malformed" anymore tho

**Comment by mr-varga** [comment]
Hi all, I have similar problem.  In the log file I found this error:

`2021-12-16 17:20:22 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/aguaiot/config_flow.py", line 67, in async_step_user
await self.hass.async_add_executor_job(agua_iot, api_url, customer_code, email, password, gen_uuid, login_api_url, brand_id)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.9/site-packages/py_agua_iot/__init__.py", line 92, in __init__
self._login()
File "/usr/local/lib/python3.9/site-packages/py_agua_iot/__init__.py", line 96, in _login
self.login()
File "/usr/local/lib/python3.9/site-packages/py_agua_iot/__init__.py", line 186, in login
claimset = jwt.decode(res['token'], verify=False)
File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 119, in decode
decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 86, in decode_complete
raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().`

Someone have further information or solution?

**Comment by TorgeTorge** [comment]
> Hello,
> 
> First I want to thank you for your HA integration of the agua iot module. I used it for like 10 month and it was working perfectly.
> 
> I recently had to wipe all my HA and rebuild it from scratch. I'm currently running on the latest stable versions which means :
> 
> * Core : core-2021.11.3
> * Supervisor : supervisor-2021.10.8
> * Home Assistant OS 6.6
> 
> I have an EvaCalor stove with an AguaIOT T009 Navel 2.0 (https://www.micronovasrl.com/en/realizzazione/t009/).
> 
> I tried to add your integration (0.0.8) but I couldn't manage to make it work. Everytime I add the aguaiot folder and restart the HA, and try to add the integration I get this error : ![2021-11-12_10-43-15](https://user-images.githubusercontent.com/44290760/141447844-09b19564-9e47-4900-9afd-5082274d4197.png)
> 
> There are no blank space or something in the fields.
> 
> I read the issues on the page and I tried to add both folders (py-agua-iot and aguaiot from the example folder) in custom_components but I still have the same issue.
> 
> Am I doing something wrong or is it something related to the new HA updates ?
> 
> Thanks !

You need to delete the "1" in the "brand id" label and write it again(always the number 1).

**Comment by Gingerator** [comment]
@TorgeTorge thank you for your answer.

I tried your workaround but i'm getting this error message :
![image](https://user-images.githubusercontent.com/44290760/147702527-6808cf57-5c9d-44ea-b353-bce03488a083.png)

**Comment by TorgeTorge** [comment]
> @TorgeTorge thank you for your answer.
> 
> I tried your workaround but i'm getting this error message : ![image](https://user-images.githubusercontent.com/44290760/147702527-6808cf57-5c9d-44ea-b353-bce03488a083.png)

Also check #24

**Comment by Gingerator** [comment]
@TorgeTorge Thank you so much, it works now.

So for those who want a quick review of what was done here :
- On this screen, you need to delete the "1" in the "Brand ID" field and then type "1" again
![image](https://user-images.githubusercontent.com/44290760/147708638-f09ed799-4121-4d04-93cc-8cc8c723976d.png)

- Then change the manifest.json like this https://github.com/fredericvl/py-agua-iot/issues/24
![image](https://user-images.githubusercontent.com/44290760/147708681-5f743815-5ae9-4f1f-9ad5-ae58602e85ef.png)
for the 0.0.8 version.

**Comment by robbiegoossens** [comment]
> > Hello,
> > First I want to thank you for your HA integration of the agua iot module. I used it for like 10 month and it was working perfectly.
> > I recently had to wipe all my HA and rebuild it from scratch. I'm currently running on the latest stable versions which means :
> > 
> > * Core : core-2021.11.3
> > * Supervisor : supervisor-2021.10.8
> > * Home Assistant OS 6.6
> > 
> > I have an EvaCalor stove with an AguaIOT T009 Navel 2.0 (https://www.micronovasrl.com/en/realizzazione/t009/).
> > I tried to add your integration (0.0.8) but I couldn't manage to make it work. Everytime I add the aguaiot folder and restart the HA, and try to add the integration I get this error : ![2021-11-12_10-43-15](https://user-images.githubusercontent.com/44290760/141447844-09b19564-9e47-4900-9afd-5082274d4197.png)
> > There are no blank space or something in the fields.
> > I read the issues on the page and I tried to add both folders (py-agua-iot and aguaiot from the example folder) in custom_components but I still have the same issue.
> > Am I doing something wrong or is it something related to the new HA updates ?
> > Thanks !
> 
> You need to delete the "1" in the "brand id" label and write it again(always the number 1).

Hi, I followed your steps, but now I get the following error:

Logger: homeassistant.setup
Source: setup.py:153
First occurred: 16:37:33 (1 occurrences)
Last logged: 16:37:33

Setup failed for aguaiot: No setup or config entry setup function defined.

Any idea on what I did wrong ?

Many thanks.

**Comment by TorgeTorge** [comment]
> 

You don't have to edit anything in configuration.yaml , just copy the plugin in costum_components folder

**Comment by robbiegoossens** [comment]
Thanks for your reply.

I did the following:

I copied the "aguaiot" folder which I found under "py-agua-iot/examples/home-assistant/custom_components/aguaiot" to my home assistant folder "custom_components"
I replaced the "__init__.py" file with the file I found under "py-agua-iot/py_agua_iot"  (Pyjwt fix (#13))
I changed the file "manifest.json" for the 0.0.8 version.

I restarted home assistant and tried to setup the integration and then I get the following error :

Logger: homeassistant.setup
Source: setup.py:153
First occurred: 16:37:33 (1 occurrences)
Last logged: 16:37:33
Setup failed for aguaiot: No setup or config entry setup function defined.

**Comment by TorgeTorge** [comment]
> Thanks for your reply.
> 
> I did the following:
> 
> I copied the "aguaiot" folder which I found under "py-agua-iot/examples/home-assistant/custom_components/aguaiot" to my home assistant folder "custom_components" I replaced the "**init**.py" file with the file I found under "py-agua-iot/py_agua_iot" (Pyjwt fix (#13)) I changed the file "manifest.json" for the 0.0.8 version.
> 
> I restarted home assistant and tried to setup the integration and then I get the following error :
> 
> Logger: homeassistant.setup Source: setup.py:153 First occurred: 16:37:33 (1 occurrences) Last logged: 16:37:33 Setup failed for aguaiot: No setup or config entry setup function defined.

You don't have to replace any file. You just need to edit the manifest.json

**Comment by robbiegoossens** [comment]
Hi, Thanks for your support, the integration is setup now.

I have 1 device and 1 entity with the correct name, but the entity is unavailable and does not give any actual values.

Any ideas what the reason can be?

**Comment by robbiegoossens** [comment]
This is the error I get :

Logger: homeassistant.components.climate
Source: custom_components/aguaiot/climate.py:110
Integration: Climate (documentation, issues)
First occurred: 18:04:15 (2 occurrences)
Last logged: 18:04:15

Error adding entities for domain climate with platform aguaiot
Error while setting up aguaiot platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _async_write_ha_state
    self.device_state_attributes is not None
  File "/config/custom_components/aguaiot/climate.py", line 110, in device_state_attributes
    ATTR_SMOKE_TEMP: self._device.gas_temperature,
  File "/usr/local/lib/python3.9/site-packages/py_agua_iot/__init__.py", line 600, in gas_temperature
    return float(self.__get_information_item('temp_gas_flue_get'))
  File "/usr/local/lib/python3.9/site-packages/py_agua_iot/__init__.py", line 430, in __get_information_item
    formula = self.__register_map_dict[item]['formula']
KeyError: 'temp_gas_flue_get'

**Comment by milouzzzz** [comment]
> Hi, Thanks for your support, the integration is setup now.
> 
> I have 1 device and 1 entity with the correct name, but the entity is unavailable and does not give any actual values.
> 
> Any ideas what the reason can be?

Same here. Never got it to work.
Never got an answer to the issue #11 i opened.
I suspect it's not a problem with this integration but with the vendor itself.
Which stove are you trying to connect?

**Comment by robbiegoossens** [comment]
I have a Nordic Fire Ilvar 9.
The integration has created a device and entity and picked up the right stove type (Ilvar9) and the right name. So there is a connection with the Agua server but I think there is an issue with the attributes names.

**Comment by nonopubli** [comment]
> @TorgeTorge Thank you so much, it works now.
> 
> So for those who want a quick review of what was done here :
> 
> * On this screen, you need to delete the "1" in the "Brand ID" field and then type "1" again
>   ![image](https://user-images.githubusercontent.com/44290760/147708638-f09ed799-4121-4d04-93cc-8cc8c723976d.png)
> * Then change the manifest.json like this [Hassio Integration problem #24](https://github.com/fredericvl/py-agua-iot/issues/24)
>   ![image](https://user-images.githubusercontent.com/44290760/147708681-5f743815-5ae9-4f1f-9ad5-ae58602e85ef.png)
>   for the 0.0.8 version.

Just followed your steps (+restart Home Assistant at the end before trying again) and it works!
Thanks a lot!!!
