### ISSUE TITLE
Easy Connect Plus Api not working

### ISSUE THREAD

**Issue by TheNetStriker** [fredericvl/py-agua-iot#22]
I habe a FreePoint ATRIUM 5 pellet oven (Uses with the Easy Connect Plus app) and I just tried to connect to the API using your library, but I'm getting the error **Connection to https://remote.mcz.it/appSignup not possible**.

I'm using the following line to connect to the api:
connection = agua_iot("https://remote.mcz.it", "746318", "email", "password", "e1b14180-a942-4550-97cf-65f647a9379b", brand_id="1")

Is there maybe also a separate url to log in for this API?

**Comment by MacArell** [comment]
Hello, I had the same problem, I managed to solve it by adding the certificate from the site https://remote.mcz.it > remote-mcz-it-chain.pem

**Comment by vincentwolsink** [comment]
See #17
