### ISSUE TITLE
Home Assistant 2022.3 and pip new dependency resolver breaks component

### ISSUE THREAD

**Issue by gzeel** [fredericvl/py-agua-iot#31]
In November 2020, with the release of Python pip 20.3, a new dependency resolver was introduced in pip, which is more strict.
Home Assistant 2022.3 uses pip version 20.3, so this new dependency resolver is used. The dependencies used by all custom components must be compatible with the ones Home Assistant uses.

Since Home Assistant uses requests 2.27.1, this should also be done by py-agua-iot.

**Comment by milouzzzz** [comment]
haven't seen any activity from fredericvl in monthes. Not sure this ever going to be fixed.

**Comment by gzeel** [comment]
> haven't seen any activity from fredericvl in monthes. Not sure this ever going to be fixed.

Let's find out. If @fredericvl doesn't respond I will take over and create a forked component.

**Comment by vincentwolsink** [comment]
I already addressed this months ago: https://github.com/fredericvl/py-agua-iot/pull/15. Unfortunately no reply.
I created a HACS compatible fork for myself, just to make things work for now: https://github.com/vincentwolsink/py-agua-iot

**Comment by gzeel** [comment]
Looks like @vincentwolsink 

> I already addressed this months ago: #15. Unfortunately no reply. I created a HACS compatible fork, just to make things work for now: https://github.com/vincentwolsink/py-agua-iot

I have seen your fork. Looks great and I am going to switch to it.

**Comment by eternalpolo** [comment]
> I already addressed this months ago: https://github.com/fredericvl/py-agua-iot/pull/15. Unfortunately no reply.
> I created a HACS compatible fork, just to make things work for now: https://github.com/vincentwolsink/py-agua-iot
> 
> 
> 

I'm testing your repository on my HA (2022.3.1) for a Piazzetta.
It works normaly for me.
I haven't tested the alarms but the basic functions seem to be ok.
Thanks a lot for your work

**Comment by marc-cizeron** [comment]
> I already addressed this months ago: #15. Unfortunately no reply. I created a HACS compatible fork, just to make things work for now: https://github.com/vincentwolsink/py-agua-iot

I use your repos as well as @eternalpolo. I have Jolly Mec stove and home assistant up to date (2022.3.1). Works great. I am available for more testing if needed.

**Comment by comperta** [comment]
Hi @vincentwolsink , with the last home assistant version I think I have a similar issue :

`Unable to install package git+https://github.com/vincentwolsink/py-agua-iot.git#py-agua-iot==0.0.8: ERROR: Cannot install py-agua-iot==0.0.8 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.`

What I am supposed to do ?

**Comment by vincentwolsink** [comment]
Hi @comperta. Remove the checkout of this repo from your home assistant installation and add my fork instead: https://github.com/vincentwolsink/py-agua-iot (You can import it directly in HACS).

**Comment by vincentwolsink** [comment]
Hi @comperta. I updated the dependencies. Should be good now.

**Comment by comperta** [comment]
Hi @vincentwolsink it's ok now, thanks you very much
