### ISSUE TITLE
Klover "unknow error"

### ISSUE THREAD

**Issue by pasqualepalmaccio** [fredericvl/py-agua-iot#35]
Hi,
i'm trying to connect klover but login process terminate with this error: 
"Unkown error, please double check configuration.".
I have tried py-agua-iot 0.0.8 and 0.0.9. 

See message error below

<img width="423" alt="Schermata 2022-09-18 alle 10 23 14" src="https://user-images.githubusercontent.com/15344383/190893013-c57741cd-e7fa-4a11-9525-5d1188b6283a.png">

**Comment by vincentwolsink** [comment]
Duplicate to #53
