### ISSUE TITLE
Dependency problems

### ISSUE THREAD

**Issue by FL100** [fredericvl/py-agua-iot#37]
When I try to add Micronova Agua IOT integration as the readme instructs I get the following error:

> Error
> Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

I check the home assistant log file and find:

> Logger: homeassistant.util.package
> Source: util/package.py:98
> First occurred: 4:14:44 pm (3 occurrences)
> Last logged: 4:15:00 pm
> 
> Unable to install package py-agua-iot==0.0.7: ERROR: Cannot install py-agua-iot==0.0.7 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by whitedevil143** [comment]
Try, 

$ sudo apt --fix-broken install 

If then also error 

Do this 

$ sudo cat /vat/lib/apt/extended_states

$ sudo apt install --reinstall $(</var/lib/apt/extended_states sed -n 's/^Package://p')

After downloaded 

Now, 
$ sudo apt --fix-broken install 

Let me know if works for you.. 
If debain then instead of apt use apt-get

**Comment by Bimboboy007** [comment]
Could you describe that in more detail so that it is also understandable for home assistant beginners.

**Comment by GregZeMachine** [comment]
Hello

I faced the same situation as described initially. It is clearly a dependency issue.
And I managed to fix it by using the following repository (imported from HACS) https://github.com/vincentwolsink/py-agua-iot

**Comment by FL100** [comment]
> Hello
> 
> I faced the same situation as described initially. It is clearly a dependency issue. And I managed to fix it by using the following repository (imported from HACS) https://github.com/vincentwolsink/py-agua-iot

Thanks for the tip. This version seams to work.

**Comment by Bimboboy007** [comment]
The version works as far as I can get the oven in the integration but I don't get any active entity.

**Comment by FL100** [comment]
Indeed. I get  "Entity is unavailable" message if addressing the entity. 

The connection with the service seams to work because it gets the type info.
