### ISSUE TITLE
Error 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by Bimboboy007** [fredericvl/py-agua-iot#40]
After the installation, when the program is called, the error comes up
500 Internal Server Error Server got itself in trouble
<img width="530" alt="Bildschirmfoto 2022-11-27 um 15 13 00" src="https://user-images.githubusercontent.com/80967872/204139802-f744216f-cb78-4be1-8cab-e22ec61065df.png">

**Comment by GauthierCrp** [comment]
Hello,

Same error, for me. I tried several months ago and the install did well. Certainly an issue due to the version of Pip

![image](https://user-images.githubusercontent.com/30144651/204248516-54763c73-7322-435f-910e-10c7fe0f4f88.png)

If anyone find the solution...

Thanks in advance,

**Comment by GauthierCrp** [comment]
OK @Bimboboy007, I found a solution.

Dependencies of this repo are not compatible anymore with HA. So I used the fork of @vincentwolsink which is more up to date in terms of dependencies.

It works fine for me, the install run well and I can Power On/Power off my stove.

Best Regards.

**Comment by Bimboboy007** [comment]
Das hat soweit funktioniert. Jetzt stehe ich aber vor dem nächsten Problem wie auch schon ein anderer erwähnt hat 
" Unknown error occurred " So wie es aussieht ist es die Brand id. Habe die Einstellung auf 1 gelassen da ich nicht weiß was ich dort eintragen soll.
