### ISSUE TITLE
down tonight ? 

### ISSUE THREAD

**Issue by silkyclouds** [fredericvl/py-agua-iot#47]
Hi all, 

Tonight (feb 16th 2023), impossible to connect the aguaiot portal. My stove can't be controlled either using the integration (aguaiot) OR the official jolly mec app. 

I believe their "cloud" is down for some reason. 

Can someone confirm that ? 
What when these people device to stop their cloud services because they are a shit company and just want to stop providing their only portal ? 

Is there a way to make their wifi module communicate with mqtt somehow to get rid of their cloud ?

**Comment by Bimboboy007** [comment]
Das wäre ein vernünftiger Lösungsansatz mit mqtt.
