### ISSUE TITLE
Retrieve Current Air Temperature

### ISSUE THREAD

**Issue by GauthierCrp** [fredericvl/py-agua-iot#51]
Hello Everyone,

I'm not a developper and I can barely read the Pyton code of this extension.
Whatever, I use this plugin to Set On or Off my Ravelli pellet stove, from Home Assistant.

I would really like to stop totally using the Ravelli application, but for that, I would like to know what is the actual temperature from the remote device. (remote controller from ravelli)

If somoene could **explain easily**, in Home Assistant : How to retrieve the current temperature and Print it in an entity or in the existing Climate entity. 

Many Thanks,;
Best Regards.

Gauthier

**Comment by jipem01** [comment]
Hello Gauthier,
  The climate entity exposed by the plugin is aware of both target and current air temp. On climate card, current is on first line, bold, and target on second line.
Using entity card, you can have access to the properties of climate entity of your stove. But it's a bit limitating.
The integration is laking of direct access to sensors.

I'm thinking to add additionnals entities for each device, mainly using sensor / bynaries sensors, to be able to uses easily data given by stove. Similar thoughts for handling alarms and popup (low wood, etc...) in HA.

As the plugin have been splitted from backend, this issue apply most to the plugin : https://github.com/vincentwolsink/home_assistant_micronova_agua_iot

**Comment by vincentwolsink** [comment]
hi @GauthierCrp and @jipem01 
In Home Assistant most of the sensors can be found in the status attributes of the climate entity.

<img width="409" alt="Scherm­afbeelding 2023-06-08 om 22 17 03" src="https://github.com/fredericvl/py-agua-iot/assets/1639734/2e41f8f5-151f-49c3-8c4e-454302fee394">

For displaying your climate entity I recommend using the [Simple Thermostat Card](https://github.com/nervetattoo/simple-thermostat).
You can also make it show those sensors clearly.

![IMG_014A72F8F425-1](https://github.com/fredericvl/py-agua-iot/assets/1639734/e593fec3-4323-492c-b2ad-173bd4a92d66)
