### ISSUE TITLE
Second Stove in Integration - Eva Calor

### ISSUE THREAD

**Issue by J0rD4n0304** [fredericvl/py-agua-iot#54]
Hi Guys, I have a second stove, I have add it in my eva calor App but he don't appear in Hassio integration ? do you have an idea what's happen ? 

Thanks in advance, Best regards

**Comment by jipem01** [comment]
After a code review, the library should be OK to handle different stove linked to the same account as it return an array of device object. But the HA plugin only create a climate entity for the first one. Fix should not be complicate.

**Comment by vincentwolsink** [comment]
Hi @J0rD4n0304, please try [home_assistant_micronova_agua_iot v0.1.1-beta1](https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/releases/tag/v0.1.1-beta1)

**Comment by J0rD4n0304** [comment]
Hi @vincentwolsink It works, tanks a lot :D
