### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by silkyclouds** [fredericvl/py-agua-iot#55]
I rcently had to migrate my HA instance, and the integration reported as "not loaded". 

I removed it, and tried to install it again : 

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

Anyone here has an idea of why I can't install the integration anymore ? 

It looks like once the repo has been added, installed via HACS, once I try to install the integration, it tries to use git to download stuff! but git is not existing in HA dockerized version (??) : 

here is what HA logs reports : 

Unable to install package git+https://github.com/vincentwolsink/py-agua-iot.git#py-agua-iot==0.0.11: ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

Thanks !

**Comment by vincentwolsink** [comment]
Hi @silkyclouds, use the Home Assistant integration from here, that should work: https://github.com/vincentwolsink/home_assistant_micronova_agua_iot

**Comment by TiebeDW** [comment]
> Hi @silkyclouds, use the Home Assistant integration from here, that should work: https://github.com/vincentwolsink/home_assistant_micronova_agua_iot

I have the same error en use the micronova_agua_iot integration.

**Comment by silkyclouds** [comment]
Hi guys,
Sorry to react that late.

i actually figured it out.

i was using the linuxserver.io docker container which for a strange reason do not include git.

after switching to the official docker container git grabbed the required requirements and it is running fine again.

**Comment by vincentwolsink** [comment]
I've forgot to create a new tag when depending back to pypi. A reinstall/update of https://github.com/vincentwolsink/home_assistant_micronova_agua_iot with v0.1.0 should fix it.
