### ISSUE TITLE
Piazzetta URL and Customer Code

### ISSUE THREAD

**Issue by securechicken** [fredericvl/py-agua-iot#6]
Hi,

Just for information, here are elementary connection details for Piazzetta brand (app name "MyPiazzetta" - they also distribute products under "Superior" brand, with a corresponding "MySuperior" app, I don't know if same hostname/code would work):
- URL: `https://piazzetta.agua-iot.com`
- Customer Code: `458632`

The MyPiazzetta app is actually not talking to piazzetta.agua-iot.com directly, but rather to what seems to be a Web proxy service (`https://piazzetta.iot.web2app.it/api/bridge/endpoint`); most certainly so they can collect usage statistics and so.
The WiFi module is however talking to piazzetta.agua-iot.com directly.

Regards.

**Comment by fredericvl** [comment]
Hi @securechicken !
Thanks for the information, I've updated the README 👍
