### ISSUE TITLE
Can't login, new customer code

### ISSUE THREAD

**Issue by rassha** [fredericvl/py-agua-iot#7]
I've tried to add integration automatically via home assistant,  but I've got error "Failed to login, please check credentials." (checked several times, it's correct)

Also, I've tried to manually enter details in configuration.yaml, but without success

Customer code is: 961328  (is for Alfaplam which connect via external navel 2.0 device)
URL is    https://alfaplam.agua-iot.com (API available at http://alfaplam.agua-iot.com:3001/api-docs/)

Mobile app for android working OK.

How do you guys managed to login?

**Comment by securechicken** [comment]
Hi @rassha,

Did you try to test the Python module from an interactive Python shell, as described in this repo README/frontpage? You might get useful hints on what is going on, and/or enable others to help you with it.

In any case, thanks for the Swagger API doc URL, it appears to be available for others brands as well, I did not know it existed, and it's very useful.

**Comment by rassha** [comment]
> Hi @rassha,
> 
> Did you try to test the Python module from an interactive Python shell, as described in this repo README/frontpage? You might get useful hints on what is going on, and/or enable others to help you with it.
> 
> In any case, thanks for the Swagger API doc URL, it appears to be available for others brands as well, I did not know it existed, and it's very useful.

Thanks for replying.

I've tried from python interactive shell as descibed in README. I got following response

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/py_agua_iot/__init__.py", line 90, in __init__
    self._login()
  File "/usr/local/lib/python3.8/site-packages/py_agua_iot/__init__.py", line 93, in _login
    self.register_app_id()
  File "/usr/local/lib/python3.8/site-packages/py_agua_iot/__init__.py", line 135, in register_app_id
    raise UnauthorizedError('Failed to register app id')
py_agua_iot.UnauthorizedError: Failed to register app id
```

**Comment by securechicken** [comment]
> I've tried from python interactive shell as descibed in README. I got following response
> 
> ```
> Traceback (most recent call last):
> py_agua_iot.UnauthorizedError: Failed to register app id
> ```

So the login was no even attempted actually; the process is failing during a previous step, which is one where an identifier describing the calling "application" is registered with the API. First guesses are that your specific brand/API endpoint might be somehow limiting use to some specific IDs (preventing such independent tool use), and/or that you somehow did not provide what is required to the API (maybe wrong customer code or app identifier).

- Could you please paste the exact connection parameters you are using (i.e. the full line of `connection = agua_iot("https://...`, without your password of course, that you can replace with say "X")?
- On top of that, how/where  did you get the customer code?

**Comment by rassha** [comment]
> > I've tried from python interactive shell as descibed in README. I got following response
> > ```
> > Traceback (most recent call last):
> > py_agua_iot.UnauthorizedError: Failed to register app id
> > ```
> 
> So the login was no even attempted actually; the process is failing during a previous step, which is one where an identifier describing the calling "application" is registered with the API. First guesses are that your specific brand/API endpoint might be somehow limiting use to some specific IDs (preventing such independent tool use), and/or that you somehow did not provide what is required to the API (maybe wrong/invalid app identifier).
> 
> * Could you please paste the exact connection parameters you are using (i.e. the full line of `connection = agua_iot("https://...`, without your password of course, that you can replace with say "X")?
> * On top of that, how/where did you get the customer code?


Here is exact connection parameters
`connection = agua_iot("https://alfaplam.agua-iot.com", "961328", "rassha@gmail.com", "xxxxxxxxxxx", "80cf9abc-3803-477b-81e0-a897c558bbcb", brand_id="1")`

Customer code is from sticker found in user manual for Navel 2.0 Device (There are also MAC address and AP Password on that sticker). Its called "Reg.Code" in User manual.

This number is needed during initial setup of android app from Google play.
[https://play.google.com/store/apps/details?id=com.micronovasrl.ninaalfaplam&hl=sr&gl=US](url)

Could it be wrong number? Maybe this number is not "customer code"?

exact URL fo Swagger I guessed by the name of manufacturer...

**Comment by securechicken** [comment]
> `connection = agua_iot("https://alfaplam.agua-iot.com", "961328", "rassha@gmail.com", "xxxxxxxxxxx", "80cf9abc-3803-477b-81e0-a897c558bbcb", brand_id="1")`
> 
> Customer code is from sticker found in user manual for Navel 2.0 Device (There are also MAC address and AP Password on that sticker). Its called "Reg.Code" in User manual.
> 
> This number is needed during initial setup of android app from Google play.
> [https://play.google.com/store/apps/details?id=com.micronovasrl.ninaalfaplam&hl=sr&gl=US](url)
> 

This is very likely not the customer code, and most probably what is causing your issue. The customer code is passed to the API as an HTTP header value during most Micronova API calls, and if it is wrong, the app registration will be failing with an HTTP 412 status code - you cannot continue with login then.

The code you obtained is required to register the Micronova module as itself, to your app provider and probably in Micronova API databases. It is not required except during first registration of your account/device in official mobile app.

Some brands/app vendors use a custom frontend user API, and it's possible that your official mobile app does not even send the required customer code to servers (but the app frontend API will then send it to the Micronova API in the background, from your brand/app vendors servers).
The Micronova IOT module itself should however send such code to the Micronova API directly.

I don't know how other codes have been obtained, if there is an easy way to get such; but I had to intercept and sniff network trafic between the Micronova IOT module and Micronova API to get the one I obtained for a specific brand. If you can do such a thing, I would recommend trying this. Other options are reverse-engineering the Android official app of your brand/stove, sniffing communications between the official app and its servers (but as said, the customer code might not even be there)... or why not trying to get in touch with Micronova API developer? :)

**Comment by rassha** [comment]
Thanks for your reply....
That's exactly what I'm going to do. I will write email to manufacturer asking for code, and while waiting for response, will try to sniff with kali linux

Will post update here

**Comment by rassha** [comment]
Success!!
I wrote email to manufacturer, and they gave me customer code. So, you can add it to list:
Alfaplam, Serbia, 
URL https://alfaplam.agua-iot.com
Customer code: 862148
[https://dodaj.rs/image/LuIeb2](url)

**Comment by fredericvl** [comment]
@securechicken Thanks for helping @rassha out 👍 

@rassha Thanks for the Alfaplam information, in the meantime it's added to the list! 👍
