### ISSUE TITLE
Problem with Piazzetta,  MyPiazzetta app version 1.9.5

### ISSUE THREAD

**Issue by dennibulgarelli** [fredericvl/py-agua-iot#72]
Hello, it worked fine until few days ago, it stopped working on home assistant, so i remove and reinstall the agua iot integration with the latest versione.
Now when i try to configure, it give me a credential error but i'm sure credentials are correct.
The version of MyPiazzetta is 1.9.5 and api version is 2.1.1.0.
When i click on link: https://piazzetta-iot.app2cloud.it/api/bridge/endpoint/, the answer is: {"Error":"INVALID_APP_ERROR","Success":false,"Source":"BRIDGE"}   
<img width="396" alt="Screenshot 2023-10-15 alle 10 27 13" src="https://github.com/fredericvl/py-agua-iot/assets/38179022/872b7695-8f7f-4909-a092-c9cedcdd20f1">

**Comment by robkrause** [comment]
Can confirm. I'm currently investigating this to hopefully get the homebridge plugin that I forked in the beginning of the year running again https://github.com/robkrause/homebridge-micronova-agua-iot-stove

Some changes that I noticed in the request header when debugging the official app with https://proxyman.io/ for iOS:
* version ist now `1.9.5`
* `id_brand` and `customer_code` are now called `idbrand` and `customercode` 
* there is an addiontal `brand` = "piazzetta" property

Will report here if I'm successful so you can benefit as well, but maybe this project is quicker.

**Comment by robkrause** [comment]
Just noticed that this is already discussed here: https://github.com/vincentwolsink/home_assistant_micronova_agua_iot/issues/55

**Comment by dennibulgarelli** [comment]
hope someone find a solution, tried some things but didn't work.

**Comment by vincentwolsink** [comment]
Probably found a fix: #73 
Please try [v0.0.22](https://github.com/fredericvl/py-agua-iot/releases/tag/v0.0.22)

**Comment by vincentwolsink** [comment]
Please try v0.0.22

**Comment by dennibulgarelli** [comment]
For me does not work unfortunately.

Il giorno dom 15 ott 2023 alle 20:23 Vincent Wolsink <
***@***.***> ha scritto:
