### ISSUE TITLE
Piazzetta URL and Customer Code

### ISSUE THREAD

**Issue by comperta** [fredericvl/py-agua-iot#8]
Hi,

I succeeded in setting up under home assistant but it does not work any more, I tried to reinstall completely but I block at the integration. I have the message: 

Failed to login, please check credentials

I know the password and username is good as it works with android app. I am using:
 MyPiazzetta (MySuperior?) 
Customer code : 458632
URL :  https://piazzetta.agua-iot.com

How can I check what's going wrong ?
FYI  there has been an update of mypiazzetta android app and since the update this home assistant plug-in stop working, maybe they change something ?

**Comment by Daavince** [comment]
I also get stuck at the login stage for my Piazzetta. Connection works with my iPhone app from myPiazzetta. I am using the python Shell with a python script and it seems to successfully pass the app register stage (as long as I use any 128-bit unique ID as described in the readme). The customer code is also the same as yours.

Could there be another verification step? I see in the python module that app register step includes a statement of phone type android. Would that cause an issue if running the script from a raspberry pi? I would assume not, given this is also used in homebridge plugin. In plain packets, there are also app-id and device-id send through (so not in the header) in case of POST statements.

If I inspect the packets, the JSON Web Token has the following payload (decoded, I removed email which was encoded):
{"id":"914EEAAD-2BBD-4D65-A050-719E75CA6D63",
"jwtid":"3ee67440-1816-41b5-bd25-b720cfbefb34",
"email":"*********",
"customer_code":"458632",
"id_app":"85397FA7-040D-4122-9AFB-AF81DC1D3162",
"id_brand":"1",
"iat":1618252175,
"exp":1618338575}

Any idea how I could try to make this work? And thanks Frederic for having created this repo, it gives me some hope to be able to integrate operation of my pellet stove with the rest of my heating system :)

**Comment by securechicken** [comment]
Hi @Daavince, @comperta 

Piazzetta recently (mid-March) changed the way they use Micronova API, and as a result it is not possible to directly login to Micronova API with Piazzetta apps users credentials anymore.
They did that to ensure users would pass through the official Piazzetta app to login, implement some non-Micronova custom functionalities, and to protect users email addresses from a disclosure to a third-party (Micronova).
As a result, py-agua-iot / Micronova PI login does not work anymore with Piazzetta brands.
Some others specifics may exist as well since these Piazzetta changes mid-March, they are still to be discovered and understood.

It is however still possible to use Micronova API endpoints (except login), by first login to Piazzetta's own servers, getting the JWT back, and then use this JWT as credential for Micronova API endpoints.

In any case, if you want to integrate with whatever your target middleware is, you will have to implement the authentication against Piazzetta servers by yourself. It's not a big deal.

You can refer to what I did for the Homebridge (Apple iOS HomeKit) integration here (JavaScript): https://github.com/securechicken/homebridge-micronova-agua-iot-stove/blob/44174f96f456a41fee4c30893f621c649b662c24/index.js#L424

**Comment by Daavince** [comment]
Hi @securechicken, thanks for getting me on the right track. I will try and find some time hopefully soon to get this implemented, good to know it is possible :)

**Comment by comperta** [comment]
Hi @securechicken  thanks for the information :)
Hope @fredericvl  will see this :)

**Comment by Daavince** [comment]
I got the login working with the guidance from @securechicken. And I am now able to request several measurements/status items from my Piazzetta stove with the python script. I am not sure how to set values yet (like turn_on or set_power to a certain value). @fredericvl: what is the synthax for adjusting values? (Vs. print(device.name + “: ” + str(device.set_power) for reading values). 
I also noticed that the mypiazzetta app communicates only with the web2app server when I inspected the packets. As securechicken mentioned, it works also directly with agua IOT server, as long as the login is done against the web2app server.

**Comment by fredericvl** [comment]
> I am not sure how to set values yet (like turn_on or set_power to a certain value). @fredericvl: what is the synthax for adjusting values? (Vs. print(device.name + “: ” + str(device.set_power) for reading values).

They're all properties so if they have a setter defined then you can change the value by setting the property (i.e. `device.set_power = 3`)
`set_air_temperature` and `set_power` are the only properties with a setter in the module.

`turn_on` and `turn_off` do not support setting values because the ON & OFF values are being retrieved automatically through the device registers map (from Agua IOT API) and then are used to turn on / off the stove.

---

Regarding the authentication part for Piazzetta, I'll check to add some flexibility to the module to make this possible.
I don't have a Piazzetta stove at my disposal so I'll need a volunteer once implemented 😄

**Comment by Daavince** [comment]
Thanks, I can do the testing. This is how it worked for me with adjusting the python code locally: 
1) I added one additional input variable to the init function (login_apiurl), which allows to provide an alternative login url to agua iot url already provided as an input. I did not strip the trailing ‘/‘ for that link, 
2) for the login step, I had to use the alternative url (https://piazzetta.iot.web2app.it/api/bridge/endpoint/, not the agua iot api), without the ‘/userLogin’ added and add two additional headers, as per suggestion securechicken: 
'applicationversion': '1.6.0'
'url':'userLogin'
Rest of the code I could leave untouched.

**Comment by comperta** [comment]
Hi all,

it looks promising, I can also test if needed :)

**Comment by fredericvl** [comment]
@Daavince @comperta 

I've created a PR on a separate branch `feature/piazzetta` with the adjusted code.
Could you please test using that branch?

When calling the module you will need to add `login_api_url="https://piazzetta.iot.web2app.it/api/bridge/endpoint/"`  to the constructor for it to work.

(FYI: if someone is using the Home Assistant example, this cannot be tested yet since this requires a release / published version to PyPI.
Once it has been successfully tested without HA, I can publish a version and update the HA example)

**Comment by Daavince** [comment]
@fredericvl 
I can test. I installed this package before on my pi using pip installer. Is there an easy way to use the separate branch __init__.py? I am a bit of a noob with Github. I have pulled from and pushed to GitHub before, but always on the master branch. tx

**Comment by comperta** [comment]
@Daavince you need to do this :
To view the remote servers that you have registered, you can run the  `git remote `command. It lists the names of the various remote references that you have specified. If you've cloned a repository, you should at least see the origin `origin` - that's the default name Git gives to the server you cloned from:

`git remote -v
origin	https://github.com/fredericvl/py-agua-iot (fetch)
origin	https://github.com/fredericvl/py-agua-iot (push)`
then use `git fetch [remote name]`
This command goes to the remote repository and retrieves any data for this project that you do not yet own. After this action, you own all the references to all the branches contained in this repository, which you can merge or inspect at any time.

To switch to an existing branch, just run the `git checkout` command. Let's switch to the new testing branch
`git checkout feature/piazzetta`

use `git log` to see the change :)

**Comment by Daavince** [comment]
Thanks @comperta, this was what I was looking for :). I will set this up with git soon and get comfortable with it. In the mean time I managed to test by copying the raw updated code into my local init.py file and tested. It works with my Piazzetta, thanks @fredericvl.

**Comment by fredericvl** [comment]
@Daavince thanks for testing! 👍 

@comperta @Daavince 
I've merged the change and created a new version 0.0.7 and also updated the HA example.

**Comment by comperta** [comment]
@fredericvl  I have : Unknown error occurred when I use integration on HA.
I use :

![Screenshot_20210418-153209](https://user-images.githubusercontent.com/21957307/115147456-585ead80-a05b-11eb-8c47-552e03159fcf.jpg)

**Comment by fredericvl** [comment]
@comperta Thanks for reporting, I've made some changes to the HA example in this commit: [Fix for 0.0.7 HA example](https://github.com/fredericvl/py-agua-iot/commit/1ef548db73491d5d6466c787a8b4b4291349072d)
Can you try it again with the updated example?

**Comment by comperta** [comment]
same here :)

in HA log I can see : 
```
Logger: aiohttp.server
Source: util/async_.py:139
First occurred: 16:53:35 (2 occurrences)
Last logged: 16:53:40

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 107, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 156, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 214, in _async_handle_step
    result: dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/aguaiot/config_flow.py", line 67, in async_step_user
    agua_iot(api_url, customer_code, email, password, gen_uuid, brand_id=brand_id, login_api_url=login_api_url)
  File "/usr/local/lib/python3.8/site-packages/py_agua_iot/__init__.py", line 92, in __init__
    self._login()
  File "/usr/local/lib/python3.8/site-packages/py_agua_iot/__init__.py", line 95, in _login
    self.register_app_id()
  File "/usr/local/lib/python3.8/site-packages/py_agua_iot/__init__.py", line 126, in register_app_id
    response = requests.post(url,
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 150, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 139, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/aguaiot/config_flow.py, line 67: agua_iot(api_url, customer_code, email, password, gen_uuid, brand_id=brand_id, login_api_url=login_api_url)

```

and a warning at boot : 

```
 Logger: homeassistant.util.async_
Source: util/async_.py:131
First occurred: 16:53:35 (2 occurrences)
Last logged: 16:53:40

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for aguaiot doing I/O at custom_components/aguaiot/config_flow.py, line 67: agua_iot(api_url, customer_code, email, password, gen_uuid, brand_id=brand_id, login_api_url=login_api_url)
```

**Comment by fredericvl** [comment]
@comperta Woops, I was testing it on an older HA version by mistake... It looks like they did change the warning from "I/O inside the event loop" to an exception which indeed breaks the example.
I've pushed a [fix](https://github.com/fredericvl/py-agua-iot/commit/2c13a68cd2dc6b5f9270fd4e84b34530fe27903d) and tested it on HA latest version and it works at my side (not a Piazzetta stove but it was broken for others too on HA latest).

Can you confirm it's fixed for you too?

**Comment by comperta** [comment]
![Capture](https://user-images.githubusercontent.com/21957307/115154408-fc0b8600-a07a-11eb-9c38-60907b133963.JPG)
thanks @fredericvl
